#!/bin/bash

alias dstop=dstop
alias dremove=dremove
alias dexec=dexec
alias dps=dps

# Stop all containers
function dstop() { docker stop $(docker ps -a -q); }

# Remove all containers
function dremove() { docker rm $(docker ps -a -q); }

# Bash into running container
function dexec() { docker exec -it $(docker ps -aqf "name=$1") bash; }

# Get container process pretty
function dps() { docker ps --format "table {{.ID}}\t{{.Names}}\t{{.Ports}}"; }
